#!/usr/bin/env bash
# Version: 0.45.0
# Created: Petr Krivan
# Project: android lab manager

# Central shell defaults for Android Lab scripts. Source this file instead of
# repeating default variable blocks in each script.

LAB_BASE="${LAB_BASE:-$HOME/AndroidLab}"
LAB_HOME="${LAB_HOME:-$LAB_BASE/android-podman-lab}"
LAB_DATA="${LAB_DATA:-$LAB_BASE/data}"
BIND_IP="${BIND_IP:-0.0.0.0}"
GPU_MODE="${GPU_MODE:-swiftshader}"

ANDROIDLAB_DEFAULT_API="${ANDROIDLAB_DEFAULT_API:-33}"
ANDROIDLAB_DEFAULT_TARGET="${ANDROIDLAB_DEFAULT_TARGET:-google_apis}"
ANDROIDLAB_DEFAULT_ARCH="${ANDROIDLAB_DEFAULT_ARCH:-x86_64}"
ANDROIDLAB_DEFAULT_DEVICE_PROFILE="${ANDROIDLAB_DEFAULT_DEVICE_PROFILE:-pixel}"

ANDROIDLAB_ADB_PORT_BASE="${ANDROIDLAB_ADB_PORT_BASE:-13555}"
ANDROIDLAB_NOVNC_PORT_BASE="${ANDROIDLAB_NOVNC_PORT_BASE:-13080}"
ANDROIDLAB_PORT_SCAN_LIMIT="${ANDROIDLAB_PORT_SCAN_LIMIT:-1000}"

ANDROIDLAB_MANAGER_HOST_DEFAULT="${ANDROIDLAB_MANAGER_HOST_DEFAULT:-0.0.0.0}"
ANDROIDLAB_MANAGER_LOCAL_HOST_DEFAULT="${ANDROIDLAB_MANAGER_LOCAL_HOST_DEFAULT:-127.0.0.1}"
ANDROIDLAB_MANAGER_PORT_DEFAULT="${ANDROIDLAB_MANAGER_PORT_DEFAULT:-18080}"
ANDROIDLAB_MANAGER_TOKEN_DEFAULT="${ANDROIDLAB_MANAGER_TOKEN_DEFAULT:-}"
ANDROIDLAB_PUBLIC_HOST_DEFAULT="${ANDROIDLAB_PUBLIC_HOST_DEFAULT:-}"

androidlab_init_web_install_defaults() {
  API="${API:-$ANDROIDLAB_DEFAULT_API}"
  TARGET="${TARGET:-$ANDROIDLAB_DEFAULT_TARGET}"
  HOST="${HOST:-$ANDROIDLAB_MANAGER_HOST_DEFAULT}"
  PORT="${PORT:-$ANDROIDLAB_MANAGER_PORT_DEFAULT}"
  TOKEN="${TOKEN:-$ANDROIDLAB_MANAGER_TOKEN_DEFAULT}"
  PUBLIC_HOST="${PUBLIC_HOST:-$ANDROIDLAB_PUBLIC_HOST_DEFAULT}"
  NO_DEFAULT="${NO_DEFAULT:-0}"
}

androidlab_init_manager_env_defaults() {
  MANAGER_HOST="${MANAGER_HOST:-$ANDROIDLAB_MANAGER_HOST_DEFAULT}"
  MANAGER_PORT="${MANAGER_PORT:-$ANDROIDLAB_MANAGER_PORT_DEFAULT}"
  MANAGER_TOKEN="${MANAGER_TOKEN:-$ANDROIDLAB_MANAGER_TOKEN_DEFAULT}"
  PUBLIC_HOST="${PUBLIC_HOST:-$ANDROIDLAB_PUBLIC_HOST_DEFAULT}"
  MANAGER_CSRF_TOKEN="${MANAGER_CSRF_TOKEN:-}"
}
