#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
# Clean bytecode generated by previous test runs.
find . -path '*/__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
fail=0
say(){ printf '[test] %s\n' "$*"; }
badflag='--video'"-bit-rate"

say 'bash syntax'
while IFS= read -r f; do bash -n "$f"; done < <(find . -type f \( -name '*.sh' -o -name 'androidlab.sh' -o -name 'install.sh' -o -name 'web-install.sh' \) | sort)

say 'no pycache packaged before tests'
if find . -path '*/__pycache__/*' -print -quit | grep -q .; then echo 'pycache found before tests' >&2; fail=1; fi

say 'python syntax'
PYTHONDONTWRITEBYTECODE=1 python3 -m py_compile manager/app.py

say 'clean-stale script present'
[[ -x scripts/clean-stale-files.sh ]] || { echo 'missing clean-stale-files.sh' >&2; fail=1; }

say 'scrcpy unsupported flag absent'
if grep -RIn --exclude='regression-test.sh' -- "$badflag" .; then
  echo "found unsupported scrcpy flag" >&2
  fail=1
fi

say 'rendered manager HTML smoke test'
TMP="$(mktemp -d)"
mkdir -p "$TMP/lab/config" "$TMP/lab/uploads" "$TMP/fake"
cat > "$TMP/lab/config/instances.tsv" <<'EOF'
old-headless	headless	13555	33	google_apis	2026-01-01
panel	novnc	13556	13080	33	google_apis	2026-01-01
EOF
cat > "$TMP/fake/flask.py" <<'PY'
class _Req:
    host='server:18080'
    form={}
    files={}
    authorization=None
request=_Req()
class Response:
    def __init__(self,*a,**k): pass
class Flask:
    def __init__(self,*a,**k): pass
    def before_request(self,f): return f
    def get(self,*a,**k): return lambda f:f
    def post(self,*a,**k): return lambda f:f
    def run(self,*a,**k): pass
PY
PYTHONDONTWRITEBYTECODE=1 LAB_HOME="$TMP/lab" PYTHONPATH="$TMP/fake:$PWD" python3 - <<'PY'
import manager.app as app
html=app.index()
assert 'Android 13 / API 33' in html, 'missing Android version preset list'
assert 'Android 16 / API 36' in html, 'missing Android 16 preset'
assert '--bit-rate 4M' in html, 'missing old-compatible scrcpy flag'
assert ('--video' + '-bit-rate') not in html, 'bad scrcpy flag rendered'
assert 'http://server:33/vnc.html' not in html, 'old record parsed API as noVNC port'
assert 'http://server:13080/vnc.html' in html, 'valid noVNC URL missing'
assert 'Open with controls' in html, 'controlled noVNC link missing'
assert '/novnc/panel' in html, 'controlled noVNC wrapper URL missing'
assert 'resize=off' in html, 'noVNC 1:1 link missing'
assert 'resize=scale' in html, 'noVNC scaled link missing'
assert 'resize=remote' in html, 'noVNC remote resize link missing'
assert 'table-wrap' in html, 'responsive table wrapper missing'
assert '<th>Status</th>' in html, 'status column missing'
assert 'power-actions' in html, 'power controls missing from cards'
assert "data-testid='spawn-device-profile'" in html, 'spawn phone model selector test id missing'
assert "data-testid='manual-device-profile'" in html, 'manual phone model selector test id missing'
assert "data-testid='instance-card-old-headless'" in html, 'instance card missing'
assert '<th>Device</th>' in html, 'device column missing'
assert 'Phone model' in html, 'phone model selector missing'
assert 'Pixel 6' in html, 'Pixel 6 option missing'
assert 'Runtime profiles' in html, 'runtime profiles section missing'
assert 'Refresh SDK device-profile list' in html, 'device profile refresh missing'
assert 'pixel_6' in html, 'pixel_6 device id missing'
assert "value='start'" in html or 'value="start"' in html, 'start lifecycle button missing'
assert "value='stop'" in html or 'value="stop"' in html, 'stop lifecycle button missing'
assert "data-testid='power-start-old-headless'" in html, 'start power test id missing'
assert "data-testid='power-stop-old-headless'" in html, 'stop power test id missing'
assert 'Phone model selector enabled' in html, 'feature proof banner missing'
assert "id='view-spawn'" in html, 'spawn view section missing'
assert "id='view-profiles'" in html, 'profiles view section missing'
assert "id='view-instances'" in html, 'instances view section missing'
assert "class='readable-table'" in html, 'readable table class missing'
assert 'Client scrcpy command</th>' not in html, 'long command column still present in table header'
assert 'status-badge' in html, 'status badge missing'
assert 'Apply size profile' in html, 'noVNC resize action missing'
assert 'Build/update image before spawn' in html, 'build-before-spawn checkbox missing'
assert 'background progress' in html, 'background progress label missing'
assert 'Apply HW + restart' in html, 'apply HW action missing'
assert 'CPU cores' in html and 'RAM MB' in html and 'Partition MB' in html, 'HW form fields missing'
assert '<th>HW</th>' in html, 'HW table column missing'
assert 'Full HD phone' in html, 'Full HD profile missing'
assert "class='hero'" in html or 'class="hero"' in html, 'modern hero missing'
assert '/static/app.js' in html and '/static/app.css' in html, 'static assets missing from rendered page'
assert '<select name=\'preset\'>' in html or '<select name="preset">' in html, 'preset select missing'
# Simulate web POST actions without a real Podman runtime.
calls=[]
def fake_run(args, env_extra=None):
    calls.append((args, env_extra))
    return 'RUN ' + ' '.join(args)
app.run = fake_run
app.image_exists = lambda api, target, mode='headless': True
app.request.form = {'name':'old-headless','op':'start'}
assert 'RUN start old-headless' in app.action(), 'web Start action did not call androidlab start'
app.request.form = {'name':'old-headless','op':'stop'}
assert 'RUN stop old-headless' in app.action(), 'web Stop action did not call androidlab stop'
app.request.form = {'name':'android-pixel6','mode':'headless','preset':'33|google_apis','device_profile':'pixel_6','device_custom':'','cpu_cores':'4','ram_mb':'8192','vm_heap_mb':'512','partition_size':'8192'}
assert 'RUN spawn android-pixel6 headless 33 google_apis pixel_6' in app.spawn(), 'web Spawn did not pass pixel_6 device profile'
assert calls[-1][1]['CPU_CORES']=='4' and calls[-1][1]['RAM_MB']=='8192', 'web Spawn did not pass HW env'
app.request.form = {'name':'old-headless','cpu_cores':'4','ram_mb':'8192','vm_heap_mb':'512','partition_size':'8192'}
assert 'RUN apply-hw old-headless' in app.apply_hw(), 'web Apply HW did not call androidlab apply-hw'
assert calls[-1][1]['CPU_CORES']=='4' and calls[-1][1]['PARTITION_SIZE']=='8192', 'web Apply HW did not pass HW env'
started=[]
def fake_start_job(title, steps):
    started.append((title, steps))
    return 'job123'
app.start_background_job = fake_start_job
app.request.form = {'name':'android-pixel6-bg','mode':'headless','preset':'36|google_apis','device_profile':'pixel_6','device_custom':'','cpu_cores':'4','ram_mb':'8192','vm_heap_mb':'512','partition_size':'8192','build_first':'1'}
job_html = app.spawn()
assert 'job_status/job123' in job_html and 'background job' in job_html, 'build-before-spawn did not return progress page'
assert started and started[-1][1][0]['args'] == ['build-api','36','google_apis','x86_64'], 'async spawn did not queue build step'
assert started[-1][1][1]['args'] == ['spawn','android-pixel6-bg','headless','36','google_apis','pixel_6'], 'async spawn did not queue spawn step'
assert started[-1][1][1]['env']['CPU_CORES'] == '4', 'async spawn did not pass HW env'
novnc_html = app.novnc_session('panel')
assert 'noVNC session: panel' in novnc_html, 'controlled noVNC route did not render session title'
assert 'data-instance-name="panel"' in novnc_html, 'controlled noVNC route did not pass instance name to template'
assert 'http://server:13080/vnc.html' in novnc_html, 'controlled noVNC route did not render direct noVNC src'
PY
rm -rf "$TMP"

say 'copy fallback present'
grep -q 'document.execCommand' manager/static/app.js || { echo 'missing execCommand fallback' >&2; fail=1; }
grep -q 'window.prompt' manager/static/app.js || { echo 'missing prompt fallback' >&2; fail=1; }

say 'API presets present'
for api in 33 34 35 36; do grep -q "'$api'" manager/definitions.py || { echo "missing API $api preset" >&2; fail=1; }; done

say 'manager CSRF support present'
grep -q 'CSRF_TOKEN' manager/app.py || { echo 'missing CSRF token support' >&2; fail=1; }
grep -q 'MANAGER_CSRF_TOKEN' scripts/install-manager-service.sh || { echo 'missing service CSRF env' >&2; fail=1; }
grep -q 'EnvironmentFile=-' scripts/install-manager-service.sh || { echo 'manager EnvironmentFile is not optional-safe' >&2; fail=1; }
grep -q 'Environment=LAB_HOME=' scripts/install-manager-service.sh || { echo 'manager unit lacks inline LAB_HOME fallback' >&2; fail=1; }
grep -q 'ExecStartPre=.*ensure-manager-env.sh' scripts/install-manager-service.sh || { echo 'manager unit does not repair manager.env before start' >&2; fail=1; }
[[ -x scripts/ensure-manager-env.sh ]] || { echo 'missing executable ensure-manager-env helper' >&2; fail=1; }
grep -q 'ensure-manager-env.sh' scripts/run-manager.sh || { echo 'run-manager does not ensure manager.env' >&2; fail=1; }
grep -q 'ensure-manager-env.sh' androidlab.sh || { echo 'base install does not ensure manager.env' >&2; fail=1; }
grep -q 'ANDROIDLAB_MANAGER_LOCAL_HOST_DEFAULT' androidlab.sh || { echo 'base install does not use central local-safe manager host default' >&2; fail=1; }

say 'manager env file install simulation'
SIMENV="$(mktemp -d)"
mkdir -p "$SIMENV/bin" "$SIMENV/home" "$SIMENV/lab"
cat > "$SIMENV/bin/systemctl" <<'SH'
#!/usr/bin/env bash
exit 0
SH
chmod +x "$SIMENV/bin/systemctl"
HOME="$SIMENV/home" LAB_HOME="$SIMENV/lab" PATH="$SIMENV/bin:$PATH" scripts/install-manager-service.sh 0.0.0.0 18080 token123 server.internal >/tmp/androidlab-manager-service-test.out
[[ -s "$SIMENV/lab/config/manager.env" ]] || { echo 'install-manager-service did not create manager.env' >&2; fail=1; }
grep -q 'MANAGER_TOKEN=token123' "$SIMENV/lab/config/manager.env" || { echo 'manager.env missing token' >&2; fail=1; }
grep -q 'PUBLIC_HOST=server.internal' "$SIMENV/lab/config/manager.env" || { echo 'manager.env missing public host' >&2; fail=1; }
grep -q 'EnvironmentFile=-' "$SIMENV/home/.config/systemd/user/androidlab-manager.service" || { echo 'service missing optional EnvironmentFile' >&2; fail=1; }
grep -q 'ExecStartPre=.*ensure-manager-env.sh' "$SIMENV/home/.config/systemd/user/androidlab-manager.service" || { echo 'service missing env repair ExecStartPre' >&2; fail=1; }
rm -rf "$SIMENV"

say 'manager env early install ordering checks'
python3 - <<'PYORDER'
from pathlib import Path
androidlab = Path('androidlab.sh').read_text()
start = androidlab.index('  install)')
end = androidlab.index('  menu)', start)
install_block = androidlab[start:end]
assert install_block.index('ensure-manager-env.sh') < install_block.index('build_api'), 'androidlab install creates manager.env after build_api'
web = Path('web-install.sh').read_text()
assert web.index('ensure-manager-env.sh') < web.index('./androidlab.sh'), 'web-install creates manager.env after androidlab install'
PYORDER

say 'no unsafe local same-line arithmetic'
if grep -RIn 'local p="\$1" end=\$((p+1000))' scripts; then echo 'unsafe local/end assignment found' >&2; fail=1; fi

say 'record removal uses field-aware awk'
if grep -RIn 'grep -v "\^.*\\t"' androidlab.sh scripts; then echo 'unsafe grep tab record removal found' >&2; fail=1; fi
grep -q "awk -F" androidlab.sh && grep -q "v n=" androidlab.sh || { echo 'missing field-aware record removal' >&2; fail=1; }

say 'port allocation helpers present'
grep -q 'port_is_allocated' androidlab.sh || { echo 'missing port_is_allocated' >&2; fail=1; }
grep -q 'repair_records' androidlab.sh || { echo 'missing repair_records' >&2; fail=1; }
grep -q 'normalize_records_file' androidlab.sh || { echo 'missing record normalization' >&2; fail=1; }
grep -q 'normalize_records_file "\$records" | awk' androidlab.sh || { echo 'list_emulators does not normalize records' >&2; fail=1; }
grep -q 'field()' scripts/enable-novnc.sh || { echo 'enable-novnc lacks robust parser' >&2; fail=1; }
grep -q 'field()' scripts/disable-novnc.sh || { echo 'disable-novnc lacks robust parser' >&2; fail=1; }


say 'noVNC sizing defaults present'
grep -q 'SCREEN="${SCREEN:-1280x900x24}"' images/emulator-novnc/entrypoint-novnc.sh || { echo 'wrong noVNC screen default' >&2; fail=1; }
grep -q 'EMULATOR_SKIN="${EMULATOR_SKIN:-540x960}"' images/emulator-novnc/entrypoint-novnc.sh || { echo 'missing emulator skin default' >&2; fail=1; }
grep -q 'resize=off' manager/app.py || { echo 'manager lacks 1:1 noVNC URL' >&2; fail=1; }
grep -q 'resize=remote' manager/app.py || { echo 'manager lacks remote resize noVNC URL' >&2; fail=1; }
grep -q 'NOVNC_PROFILES' manager/definitions.py || { echo 'manager lacks noVNC profiles' >&2; fail=1; }
grep -q "'fullhd'" manager/definitions.py || { echo 'manager lacks fullhd profile' >&2; fail=1; }
grep -q 'Full HD phone' manager/definitions.py || { echo 'manager lacks fullhd label' >&2; fail=1; }
grep -q 'table-wrap' manager/app.py || { echo 'manager lacks responsive table wrapper' >&2; fail=1; }


say 'v23 hardening checks present'
grep -q 'guard_lab_paths' androidlab.sh || { echo 'missing path guard' >&2; fail=1; }
grep -q 'Instance already exists in records' androidlab.sh || { echo 'missing duplicate name guard' >&2; fail=1; }
grep -q 'Failed to start emulator container; removing pod' androidlab.sh || { echo 'missing pod cleanup on run failure' >&2; fail=1; }
grep -q 'Invalid whitespace/comment character' scripts/install-manager-service.sh || { echo 'missing env value validation' >&2; fail=1; }
grep -q 'Manager token is empty' web-install.sh || { echo 'missing no-token warning' >&2; fail=1; }


say 'v23 web action safety checks present'
grep -q 'def run_result' manager/app.py || { echo 'missing run_result' >&2; fail=1; }
grep -q 'Invalid action' manager/app.py || { echo 'unknown actions may still fall through' >&2; fail=1; }
grep -q 'valid_mode' manager/app.py || { echo 'missing mode validation' >&2; fail=1; }
grep -q 'valid_api_target' manager/app.py || { echo 'missing API/target validation' >&2; fail=1; }
grep -q 'if code != 0' manager/app.py || { echo 'resize does not stop on disable failure' >&2; fail=1; }


say 'v23 dark theme checks present'
grep -q 'color-scheme: dark' manager/static/app.css || { echo 'missing dark color scheme' >&2; fail=1; }
[[ ! -f docs/DARK_THEME_V18.md ]] || grep -q 'DARK_THEME_V18' docs/DARK_THEME_V18.md || true
grep -q 'radial-gradient' manager/static/app.css || { echo 'missing dark visual background' >&2; fail=1; }
grep -q 'linear-gradient(180deg,#0ea5e9,#0284c7)' manager/static/app.css || { echo 'missing professional button gradient' >&2; fail=1; }


say 'v23 sidebar/dashboard checks present'
grep -R -q 'app-shell' manager/templates manager/static || { echo 'missing app shell layout' >&2; fail=1; }
grep -R -q 'side-nav' manager/templates manager/static || { echo 'missing side navigation' >&2; fail=1; }
grep -q 'stats_html' manager/app.py || { echo 'missing stats cards' >&2; fail=1; }
grep -q 'filterInstances' manager/static/app.js || { echo 'missing instance filter JS' >&2; fail=1; }
grep -q 'instance-row' manager/app.py || { echo 'missing filterable instance rows' >&2; fail=1; }


say 'v23 documentation checks present'
[[ -f docs/ADB_CHEATSHEET.md ]] || { echo 'missing ADB cheat sheet' >&2; fail=1; }
[[ -f docs/FRIDA_CHEATSHEET.md ]] || { echo 'missing Frida cheat sheet' >&2; fail=1; }
grep -q 'def render_markdown' manager/app.py || { echo 'missing markdown renderer' >&2; fail=1; }
grep -q 'docs-grid' manager/app.py || { echo 'missing professional docs grid' >&2; fail=1; }
grep -q 'doc-body' manager/app.py || { echo 'missing professional doc body styling' >&2; fail=1; }


say 'v23 docs polish checks present'
grep -q 'def doc_meta' manager/app.py || { echo 'missing doc metadata helper' >&2; fail=1; }
grep -q 'filterDocs' manager/static/app.js || { echo 'missing docs filter JS' >&2; fail=1; }
grep -q 'doc-category' manager/app.py || { echo 'missing categorized docs UI' >&2; fail=1; }
grep -q 'code-block' manager/app.py || { echo 'missing improved code block renderer' >&2; fail=1; }
grep -q 'md-table' manager/app.py || { echo 'missing markdown table renderer' >&2; fail=1; }
grep -q 'ADB Cheat Sheet' docs/ADB_CHEATSHEET.md || { echo 'missing ADB cheat sheet title' >&2; fail=1; }
grep -q 'Frida Cheat Sheet' docs/FRIDA_CHEATSHEET.md || { echo 'missing Frida cheat sheet title' >&2; fail=1; }


say 'v23 docs/sidebar navigation checks present'
grep -R -q "/?view=spawn#spawn" manager/templates manager/app.py || { echo 'sidebar spawn link is not robust absolute view URL' >&2; fail=1; }
grep -R -q "/?view=instances#instances" manager/templates manager/app.py || { echo 'sidebar instances link is not robust absolute view URL' >&2; fail=1; }
if grep -q "href='#spawn'" manager/app.py; then echo 'found broken page-local sidebar spawn link' >&2; fail=1; fi
if grep -q "href='#instances'" manager/app.py; then echo 'found broken page-local sidebar instances link' >&2; fail=1; fi


say 'v23 running instance discovery checks present'
grep -q 'discover_running' androidlab.sh || { echo 'missing discover_running command' >&2; fail=1; }
grep -q 'published_port' androidlab.sh || { echo 'missing published port helper' >&2; fail=1; }
grep -q 'Discover running pods' manager/app.py || { echo 'missing web discover button' >&2; fail=1; }
grep -q 'discover-running' web-install.sh || { echo 'web install does not run discovery' >&2; fail=1; }
grep -q 'SKIP_KVM_CHECK' androidlab.sh || { echo 'missing test-only KVM check bypass' >&2; fail=1; }

say 'v23 fake podman runtime discovery simulation'
SIM="$(mktemp -d)"
mkdir -p "$SIM/fake" "$SIM/data"
cat > "$SIM/fake/podman" <<'POD'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "pod" && "${2:-}" == "ls" ]]; then echo android-emu13-nostore; exit 0; fi
if [[ "${1:-}" == "container" && "${2:-}" == "exists" ]]; then [[ "${3:-}" == "android-emu13-nostore-emulator" ]]; exit $?; fi
if [[ "${1:-}" == "port" ]]; then
  if [[ "${2:-}" == "android-emu13-nostore-emulator" && "${3:-}" == "5555/tcp" ]]; then echo "0.0.0.0:13555"; exit 0; fi
  if [[ "${2:-}" == "android-emu13-nostore-emulator" && "${3:-}" == "6080/tcp" ]]; then exit 0; fi
fi
if [[ "${1:-}" == "pod" && "${2:-}" == "inspect" ]]; then exit 0; fi
if [[ "${1:-}" == "inspect" && "${2:-}" == "android-emu13-nostore-emulator" ]]; then
  joined="$*"
  case "$joined" in
    *Config.Env*) echo "ANDROID_API=33"; echo "ANDROID_TARGET=google_apis"; exit 0 ;;
    *ImageName*) echo "localhost/android-emulator-headless:api33-google_apis-x86_64"; exit 0 ;;
    *Created*) echo "2026-06-15T20:03:01+02:00"; exit 0 ;;
  esac
fi
exit 0
POD
chmod +x "$SIM/fake/podman"
PATH="$SIM/fake:$PATH" LAB_BASE="$SIM" LAB_HOME="$SIM/lab" LAB_DATA="$SIM/data" SKIP_KVM_CHECK=1 ./androidlab.sh discover-running >/dev/null
if ! grep -q $'android-emu13-nostore\theadless\t13555\t\t33\tgoogle_apis' "$SIM/lab/config/instances.tsv"; then
  echo 'fake runtime discovery did not recover running headless instance' >&2
  cat "$SIM/lab/config/instances.tsv" >&2 || true
  fail=1
fi
rm -rf "$SIM"


say 'v24 stop/start lifecycle checks present'
grep -q 'stop_emulator()' androidlab.sh || { echo 'missing stop_emulator function' >&2; fail=1; }
grep -q 'start_emulator()' androidlab.sh || { echo 'missing start_emulator function' >&2; fail=1; }
grep -q 'pod_state()' androidlab.sh || { echo 'missing pod_state function' >&2; fail=1; }
grep -q "stop) ensure_canonical" androidlab.sh || { echo 'missing stop CLI command' >&2; fail=1; }
grep -q "start) ensure_canonical" androidlab.sh || { echo 'missing start CLI command' >&2; fail=1; }
grep -q "state) ensure_canonical" androidlab.sh || { echo 'missing state CLI command' >&2; fail=1; }
grep -q 'def pod_state' manager/app.py || { echo 'manager missing pod_state helper' >&2; fail=1; }
grep -q "value='stop'" manager/app.py || { echo 'manager missing Stop action' >&2; fail=1; }
grep -q "value='start'" manager/app.py || { echo 'manager missing Start action' >&2; fail=1; }
grep -q '<th>Status</th>' manager/app.py || { echo 'manager missing Status column' >&2; fail=1; }
grep -q 'power-actions' manager/app.py || { echo 'manager missing card power controls' >&2; fail=1; }
grep -q 'power-actions' manager/app.py || { echo 'manager missing power actions form' >&2; fail=1; }
grep -q 'status-badge' manager/app.py || { echo 'manager missing status badge styles' >&2; fail=1; }

say 'v24 fake podman start/stop simulation'
SIM2="$(mktemp -d)"
mkdir -p "$SIM2/fake" "$SIM2/data"
cat > "$SIM2/fake/podman" <<'POD'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "pod" && "${2:-}" == "exists" ]]; then [[ "${3:-}" == "emu" ]]; exit $?; fi
if [[ "${1:-}" == "pod" && "${2:-}" == "stop" ]]; then [[ "${3:-}" == "emu" ]] && echo emu && exit 0; fi
if [[ "${1:-}" == "pod" && "${2:-}" == "start" ]]; then [[ "${3:-}" == "emu" ]] && echo emu && exit 0; fi
if [[ "${1:-}" == "pod" && "${2:-}" == "inspect" ]]; then echo "Running"; exit 0; fi
exit 0
POD
chmod +x "$SIM2/fake/podman"
PATH="$SIM2/fake:$PATH" LAB_BASE="$SIM2" LAB_HOME="$SIM2/lab" LAB_DATA="$SIM2/data" SKIP_KVM_CHECK=1 ./androidlab.sh stop emu | grep -q 'Stopped emu' || { echo 'fake stop failed' >&2; fail=1; }
PATH="$SIM2/fake:$PATH" LAB_BASE="$SIM2" LAB_HOME="$SIM2/lab" LAB_DATA="$SIM2/data" SKIP_KVM_CHECK=1 ./androidlab.sh start emu | grep -q 'Started emu' || { echo 'fake start failed' >&2; fail=1; }
PATH="$SIM2/fake:$PATH" LAB_BASE="$SIM2" LAB_HOME="$SIM2/lab" LAB_DATA="$SIM2/data" SKIP_KVM_CHECK=1 ./androidlab.sh state emu | grep -q 'Running' || { echo 'fake state failed' >&2; fail=1; }
rm -rf "$SIM2"


say 'v25 phone model/device profile checks present'
grep -q 'validate_device_profile' androidlab.sh || { echo 'missing device profile validation' >&2; fail=1; }
grep -q 'device_presets' androidlab.sh || { echo 'missing device presets CLI' >&2; fail=1; }
grep -q 'DEVICE_PROFILE="$device_profile"' androidlab.sh || { echo 'emulator container does not receive DEVICE_PROFILE' >&2; fail=1; }
grep -q 'DEVICE_PROFILE="${5:-$ANDROIDLAB_DEFAULT_DEVICE_PROFILE}"' scripts/spawn-emulator.sh || { echo 'spawn script does not accept centralized device profile default' >&2; fail=1; }
grep -q 'device_profile_options' manager/app.py || { echo 'manager missing device profile selector helper' >&2; fail=1; }
grep -q 'Phone model' manager/app.py || { echo 'manager missing phone model UI' >&2; fail=1; }
grep -q '<th>Device</th>' manager/app.py || { echo 'manager missing Device column' >&2; fail=1; }
grep -q 'pixel_6' manager/app.py || { echo 'manager missing Pixel 6 profile' >&2; fail=1; }

say 'v25 fake podman create with phone model simulation'
SIM3="$(mktemp -d)"
mkdir -p "$SIM3/fake" "$SIM3/data"
cat > "$SIM3/fake/podman" <<'POD'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "image" && "${2:-}" == "exists" ]]; then exit 0; fi
if [[ "${1:-}" == "pod" && "${2:-}" == "exists" ]]; then exit 1; fi
if [[ "${1:-}" == "network" && "${2:-}" == "exists" ]]; then exit 0; fi
if [[ "${1:-}" == "network" && "${2:-}" == "create" ]]; then echo net; exit 0; fi
if [[ "${1:-}" == "pod" && "${2:-}" == "create" ]]; then echo podid; exit 0; fi
if [[ "${1:-}" == "run" ]]; then echo containerid; exit 0; fi
if [[ "${1:-}" == "pod" && "${2:-}" == "rm" ]]; then exit 0; fi
exit 0
POD
cat > "$SIM3/fake/ss" <<'SS'
#!/usr/bin/env bash
exit 0
SS
chmod +x "$SIM3/fake/podman" "$SIM3/fake/ss"
PATH="$SIM3/fake:$PATH" LAB_BASE="$SIM3" LAB_HOME="$SIM3/lab" LAB_DATA="$SIM3/data" SKIP_KVM_CHECK=1 ./androidlab.sh create emu-pixel6 13555 headless 33 google_apis pixel_6 >/dev/null
if ! grep -q $'emu-pixel6\theadless\t13555\t\t33\tgoogle_apis\t' "$SIM3/lab/config/instances.tsv"; then
  echo 'fake create did not write instance record' >&2
  cat "$SIM3/lab/config/instances.tsv" >&2 || true
  fail=1
fi
if ! awk -F'\t' '$1=="emu-pixel6" && $8=="pixel_6" {found=1} END{exit found?0:1}' "$SIM3/lab/config/instances.tsv"; then
  echo 'fake create did not preserve pixel_6 device profile' >&2
  cat "$SIM3/lab/config/instances.tsv" >&2 || true
  fail=1
fi
rm -rf "$SIM3"


say 'v26 code review hardening checks present'
grep -q 'Image missing before mode switch' scripts/enable-novnc.sh || { echo 'enable-novnc lacks image preflight' >&2; fail=1; }
grep -q 'Image missing before mode switch' scripts/disable-novnc.sh || { echo 'disable-novnc lacks image preflight' >&2; fail=1; }
grep -q 'noVNC port already allocated/listening before mode switch' scripts/enable-novnc.sh || { echo 'enable-novnc lacks pre-delete noVNC port check' >&2; fail=1; }
grep -q 'Device profile too long' androidlab.sh || { echo 'CLI lacks device profile length validation' >&2; fail=1; }
grep -q 'len(device or .*) <= 64' manager/app.py || { echo 'manager lacks device profile length validation' >&2; fail=1; }
grep -q 'Invalid --port' web-install.sh || { echo 'web-install lacks port validation' >&2; fail=1; }

say 'v26 fake noVNC image-preflight simulation'
SIM4="$(mktemp -d)"
mkdir -p "$SIM4/lab/config" "$SIM4/fake"
cat > "$SIM4/lab/config/instances.tsv" <<'EOF'
emu	headless	13555		33	google_apis	2026-01-01T00:00:00+00:00	pixel_6
EOF
cat > "$SIM4/lab/androidlab.sh" <<'LAB'
#!/usr/bin/env bash
echo "androidlab called unexpectedly $*" > "$LAB_HOME/delete-called"
exit 1
LAB
chmod +x "$SIM4/lab/androidlab.sh"
cat > "$SIM4/fake/podman" <<'POD'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "image" && "${2:-}" == "exists" ]]; then exit 1; fi
if [[ "${1:-}" == "pod" && "${2:-}" == "rm" ]]; then echo "pod rm called" > "$LAB_HOME/pod-rm-called"; exit 0; fi
exit 0
POD
cat > "$SIM4/fake/ss" <<'SS'
#!/usr/bin/env bash
exit 0
SS
chmod +x "$SIM4/fake/podman" "$SIM4/fake/ss"
if PATH="$SIM4/fake:$PATH" LAB_HOME="$SIM4/lab" ./scripts/enable-novnc.sh emu 13080 >/tmp/v26-enable.out 2>/tmp/v26-enable.err; then
  echo 'enable-novnc unexpectedly succeeded with missing target image' >&2
  fail=1
fi
grep -q 'Image missing before mode switch' /tmp/v26-enable.err || { echo 'enable-novnc did not report image preflight failure' >&2; cat /tmp/v26-enable.err >&2; fail=1; }
[[ ! -f "$SIM4/lab/delete-called" && ! -f "$SIM4/lab/pod-rm-called" ]] || { echo 'enable-novnc deleted/current pod before preflight failure' >&2; fail=1; }
rm -rf "$SIM4" /tmp/v26-enable.out /tmp/v26-enable.err


say 'v27 device profile discovery checks present'
grep -q 'device_list()' androidlab.sh || { echo 'missing device_list function' >&2; fail=1; }
grep -q 'avdmanager list device' androidlab.sh || { echo 'device_list does not call avdmanager list device' >&2; fail=1; }
grep -q 'device-list) ensure_canonical' androidlab.sh || { echo 'missing device-list CLI command' >&2; fail=1; }
grep -q 'DEVICE_CACHE' manager/app.py || { echo 'manager lacks device cache' >&2; fail=1; }
grep -q 'Runtime profiles' manager/app.py || { echo 'manager lacks Runtime profiles section' >&2; fail=1; }
grep -R -q "/?view=profiles#profiles" manager/templates manager/app.py || { echo 'sidebar lacks Profiles robust view link' >&2; fail=1; }
grep -q "@app.post('/device_list')" manager/app.py || { echo 'manager lacks device_list route' >&2; fail=1; }

say 'v27 fake device-list refresh simulation'
SIM5="$(mktemp -d)"
mkdir -p "$SIM5/fake" "$SIM5/data"
cat > "$SIM5/fake/podman" <<'POD'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "images" ]]; then echo "localhost/android-emulator-headless:api33-google_apis-x86_64"; exit 0; fi
if [[ "${1:-}" == "run" ]]; then printf 'pixel_6\tPixel 6\npixel_8\tPixel 8\n'; exit 0; fi
exit 0
POD
chmod +x "$SIM5/fake/podman"
PATH="$SIM5/fake:$PATH" LAB_BASE="$SIM5" LAB_HOME="$SIM5/lab" LAB_DATA="$SIM5/data" SKIP_KVM_CHECK=1 ./androidlab.sh device-list >/dev/null
if ! grep -q $'pixel_6\tPixel 6' "$SIM5/lab/config/device-list.txt"; then
  echo 'fake device-list did not write SDK device cache' >&2
  cat "$SIM5/lab/config/device-list.txt" >&2 || true
  fail=1
fi
rm -rf "$SIM5"


say 'v28 visible power controls checks present'
grep -q 'power-actions' manager/app.py || { echo 'missing visible power controls' >&2; fail=1; }
grep -q "value='start'" manager/app.py || { echo 'missing visible Start button' >&2; fail=1; }
grep -q "value='stop'" manager/app.py || { echo 'missing visible Stop button' >&2; fail=1; }
[[ -f docs/POWER_CONTROLS.md ]] || { echo 'missing power controls doc' >&2; fail=1; }


say 'v29 verified UI feature checks present'
grep -q "data-testid='spawn-device-profile'" manager/app.py || { echo 'missing stable spawn device selector marker' >&2; fail=1; }
grep -q "data-testid='manual-device-profile'" manager/app.py || { echo 'missing stable manual device selector marker' >&2; fail=1; }
grep -q "data-testid='power-start-" manager/app.py || { echo 'missing stable Start button marker' >&2; fail=1; }
grep -q "data-testid='power-stop-" manager/app.py || { echo 'missing stable Stop button marker' >&2; fail=1; }
grep -q 'instance-cards' manager/app.py || { echo 'missing visible instance cards' >&2; fail=1; }
grep -q 'Phone model selector enabled' manager/app.py || { echo 'missing feature proof banner' >&2; fail=1; }


say 'v30 organized UI checks present'
grep -q 'function showSection' manager/static/app.js || { echo 'missing section switcher JS' >&2; fail=1; }
grep -q "id='view-spawn'" manager/app.py || { echo 'missing Spawn view' >&2; fail=1; }
grep -q "id='view-profiles'" manager/app.py || { echo 'missing Profiles view' >&2; fail=1; }
grep -q "id='view-instances'" manager/app.py || { echo 'missing Instances view' >&2; fail=1; }
grep -q "class='readable-table'" manager/app.py || { echo 'missing readable table' >&2; fail=1; }
grep -q 'tr.instance-row,.instance-card' manager/static/app.js || { echo 'instance filter does not handle cards and table rows' >&2; fail=1; }
if grep -q 'Client scrcpy command</th>' manager/app.py; then echo 'long scrcpy command column still in table' >&2; fail=1; fi
[[ -f docs/WEB_MANAGER.md ]] || { echo 'missing web manager help doc' >&2; fail=1; }



say 'v31 fake api-list entrypoint override simulation'
SIM6="$(mktemp -d)"
mkdir -p "$SIM6/fake" "$SIM6/data"
cat > "$SIM6/fake/podman" <<'POD'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "images" ]]; then echo "localhost/android-emulator-headless:api33-google_apis-x86_64"; exit 0; fi
if [[ "${1:-}" == "run" ]]; then
  if [[ "$*" != *"--entrypoint bash"* ]]; then echo "missing --entrypoint bash" >&2; exit 7; fi
  printf 'system-images;android-33;google_apis;x86_64\nsystem-images;android-36;google_apis_playstore;x86_64\n'
  exit 0
fi
exit 0
POD
chmod +x "$SIM6/fake/podman"
PATH="$SIM6/fake:$PATH" LAB_BASE="$SIM6" LAB_HOME="$SIM6/lab" LAB_DATA="$SIM6/data" SKIP_KVM_CHECK=1 ./androidlab.sh api-list >/dev/null
if ! grep -q 'system-images;android-36;google_apis_playstore;x86_64' "$SIM6/lab/config/api-list.txt"; then
  echo 'fake api-list did not write SDK API cache' >&2
  cat "$SIM6/lab/config/api-list.txt" >&2 || true
  fail=1
fi
rm -rf "$SIM6"


say 'v31 hardware and build-before-spawn checks present'
grep -q -- '--entrypoint bash' androidlab.sh || { echo 'api/device list still runs emulator entrypoint' >&2; fail=1; }
grep -q 'CPU_CORES' images/emulator-headless/entrypoint.sh || { echo 'headless entrypoint lacks CPU_CORES' >&2; fail=1; }
grep -q 'CPU_CORES' images/emulator-novnc/entrypoint-novnc.sh || { echo 'novnc entrypoint lacks CPU_CORES' >&2; fail=1; }
grep -q 'apply-hw' androidlab.sh || { echo 'missing apply-hw CLI command' >&2; fail=1; }
[[ -x scripts/apply-hw.sh ]] || { echo 'missing apply-hw script' >&2; fail=1; }
grep -q 'Build/update image before spawn' manager/app.py || { echo 'missing build-before-spawn UI' >&2; fail=1; }
grep -q 'image_exists' manager/app.py || { echo 'manager lacks image existence check' >&2; fail=1; }
grep -R -q 'Back to Profiles' manager || { echo 'section-specific Back links missing' >&2; fail=1; }

say 'v32 async progress job checks present'
grep -q 'start_background_job' manager/app.py || { echo 'missing background job helper' >&2; fail=1; }
grep -q 'job_runner.py' manager/app.py || { echo 'manager does not launch job runner' >&2; fail=1; }
[[ -x manager/job_runner.py ]] || { echo 'missing executable job runner' >&2; fail=1; }
grep -q "@app.get('/job_status/<job_id>')" manager/app.py || { echo 'missing job status route' >&2; fail=1; }
grep -q 'pollJob' manager/static/app.js || { echo 'missing progress polling JS' >&2; fail=1; }
grep -q 'background progress' manager/app.py || { echo 'missing background progress UI label' >&2; fail=1; }

say 'v33 instance layout polish checks present'
grep -q 'instance-layout' manager/app.py || { echo 'missing structured instance layout' >&2; fail=1; }
grep -q 'danger-zone' manager/app.py || { echo 'missing danger zone grouping' >&2; fail=1; }
grep -q 'table is compact/read-only' manager/app.py || { echo 'missing compact table explanation' >&2; fail=1; }
grep -q 'white-space:nowrap' manager/static/app.css || { echo 'table cells can still wrap vertically' >&2; fail=1; }
if grep -q '<th>Actions</th>' manager/app.py; then echo 'Actions column still present in compact table' >&2; fail=1; fi
if grep -q '<th>Power</th>' manager/app.py; then echo 'Power column still present in compact table' >&2; fail=1; fi

say 'v34 robust sidebar navigation checks present'
grep -q 'viewFromLocation' manager/static/app.js || { echo 'missing viewFromLocation helper' >&2; fail=1; }
grep -q 'viewUrl' manager/static/app.js || { echo 'missing robust viewUrl helper' >&2; fail=1; }
grep -q 'history.pushState' manager/static/app.js || { echo 'missing pushState navigation' >&2; fail=1; }
grep -q 'popstate' manager/static/app.js || { echo 'missing browser back/forward handler' >&2; fail=1; }
grep -R -q "/?view=spawn#spawn" manager || { echo 'spawn link not robust' >&2; fail=1; }
if grep -R -q "href='/#spawn'" manager; then echo 'old hash-only spawn link still present' >&2; fail=1; fi

say 'v35 noVNC phone control checks present'
grep -q 'adb_keyevent' androidlab.sh || { echo 'missing adb keyevent CLI helper' >&2; fail=1; }
grep -q "key) ensure_canonical" androidlab.sh || { echo 'missing key CLI command' >&2; fail=1; }
grep -q "@app.get('/novnc/<name>')" manager/app.py || { echo 'missing controlled noVNC wrapper route' >&2; fail=1; }
grep -q "@app.post('/keyevent')" manager/app.py || { echo 'missing keyevent web route' >&2; fail=1; }
grep -q 'sendKey' manager/static/app.js || { echo 'missing noVNC phone control JS' >&2; fail=1; }
grep -q '◀ Back' manager/templates/novnc.html || { echo 'missing Back phone control button' >&2; fail=1; }
grep -q '● Home' manager/templates/novnc.html || { echo 'missing Home phone control button' >&2; fail=1; }
grep -q '■ Recents' manager/templates/novnc.html || { echo 'missing Recents phone control button' >&2; fail=1; }
grep -q 'input keyevent' androidlab.sh || { echo 'CLI key command does not use adb input keyevent' >&2; fail=1; }


say 'v42 split asset/header checks present'
for f in manager/app.py manager/definitions.py manager/templates/base.html manager/templates/job.html manager/templates/novnc.html manager/static/app.css manager/static/app.js scripts/install-manager-service.sh scripts/run-manager.sh scripts/ensure-manager-env.sh androidlab.sh web-install.sh scripts/init-vars.sh client-rocky-scrcpy/client-init-vars.sh client-rocky-scrcpy/install-client.sh client-rocky-scrcpy/run-scrcpy.sh; do
  grep -q 'Version: 0.45.0' "$f" || { echo "missing version header in $f" >&2; fail=1; }
  grep -q 'Created: Petr Krivan' "$f" || { echo "missing creator header in $f" >&2; fail=1; }
  grep -q 'Project: android lab manager' "$f" || { echo "missing project header in $f" >&2; fail=1; }
done
grep -q 'API_PRESETS' manager/definitions.py || { echo 'API presets were not split to definitions.py' >&2; fail=1; }
grep -q 'NOVNC_PROFILES' manager/definitions.py || { echo 'noVNC profiles were not split to definitions.py' >&2; fail=1; }
grep -q 'DEVICE_PROFILES' manager/definitions.py || { echo 'device profiles were not split to definitions.py' >&2; fail=1; }
grep -q '<link rel="stylesheet"' manager/templates/base.html || { echo 'base template does not load split CSS' >&2; fail=1; }
grep -q 'script defer src' manager/templates/base.html || { echo 'base template does not load split JS' >&2; fail=1; }
if grep -q '<style>' manager/app.py; then echo 'inline style block still present in app.py' >&2; fail=1; fi


say 'v42 centralized shell init variable checks present'
grep -q 'ANDROIDLAB_DEFAULT_API' scripts/init-vars.sh || { echo 'missing centralized default API' >&2; fail=1; }
grep -q 'ANDROIDLAB_MANAGER_PORT_DEFAULT' scripts/init-vars.sh || { echo 'missing centralized manager port default' >&2; fail=1; }
grep -q 'ANDROIDLAB_ADB_PORT_BASE' scripts/init-vars.sh || { echo 'missing centralized ADB port base' >&2; fail=1; }
grep -q 'ANDROIDLAB_NOVNC_PORT_BASE' scripts/init-vars.sh || { echo 'missing centralized noVNC port base' >&2; fail=1; }
grep -q 'scripts/init-vars.sh' androidlab.sh || { echo 'androidlab.sh does not source init-vars' >&2; fail=1; }
grep -q 'scripts/init-vars.sh' web-install.sh || { echo 'web-install.sh does not source init-vars' >&2; fail=1; }
grep -q 'init-vars.sh' scripts/spawn-emulator.sh || { echo 'spawn-emulator.sh does not source init-vars' >&2; fail=1; }
grep -q 'client-init-vars.sh' client-rocky-scrcpy/install-client.sh || { echo 'client install does not source client-init-vars' >&2; fail=1; }
grep -q 'ANDROIDLAB_SCRCPY_IMAGE' client-rocky-scrcpy/client-init-vars.sh || { echo 'missing centralized client image default' >&2; fail=1; }


say 'v43 raw client ADB documentation checks present'
for f in docs/ADB_CHEATSHEET.md docs/FRIDA_CHEATSHEET.md client-rocky-scrcpy/docs/ADB_COOKBOOK.md client-rocky-scrcpy/README.md; do
  if grep -q 'androidlab-adb\|androidlab-settings\|androidlab-quicksettings\|androidlab-notifications' "$f"; then
    echo "ADB docs still reference Android Lab ADB/settings wrappers in $f" >&2
    fail=1
  fi
done
grep -q 'adb connect SERVER_INTERNAL_IP:13555' docs/ADB_CHEATSHEET.md || { echo 'ADB cheat sheet lacks raw client adb connect example' >&2; fail=1; }
grep -q 'adb -s SERVER_INTERNAL_IP:13555' docs/ADB_CHEATSHEET.md || { echo 'ADB cheat sheet lacks adb -s serial examples' >&2; fail=1; }
grep -q 'ANDROID_SERIAL=SERVER_INTERNAL_IP:13555' docs/ADB_CHEATSHEET.md || { echo 'ADB cheat sheet lacks ANDROID_SERIAL example' >&2; fail=1; }
grep -q 'localhost:5555 offline' docs/ADB_CHEATSHEET.md || { echo 'ADB cheat sheet lacks stale localhost offline cleanup note' >&2; fail=1; }
grep -q 'emulator runs on the server\|The emulator runs on the server' docs/ADB_CHEATSHEET.md || { echo 'ADB cheat sheet does not explain server/client boundary' >&2; fail=1; }

say 'v44 documentation metadata header cleanup checks present'
if grep -RIn '^Version: .*\|^Created: Petr Krivan\|^Project: android lab manager' docs/*.md client-rocky-scrcpy/docs/*.md README.md client-rocky-scrcpy/README.md; then
  echo 'documentation metadata headers still present' >&2
  fail=1
fi
if grep -RIn '<!--[[:space:]]*$' docs/*.md client-rocky-scrcpy/docs/*.md README.md client-rocky-scrcpy/README.md | grep -q .; then
  echo 'documentation HTML comment header marker still present' >&2
  fail=1
fi
if find docs -maxdepth 1 -type f -name '*_V[0-9]*.md' | grep -q .; then echo 'version-specific docs still present' >&2; find docs -maxdepth 1 -type f -name '*_V[0-9]*.md' >&2; fail=1; fi


say 'v45 help-only documentation set checks present'
if find docs -maxdepth 1 -type f \( -name '*_V[0-9]*.md' -o -name '*V[0-9]*.md' -o -name 'CODE_REVIEW*.md' -o -name 'SOURCE_REVIEW*.md' -o -name 'REGRESSION_TESTS.md' -o -name 'RUNTIME_SIMULATION.md' -o -name 'DOC_HEADERS*.md' -o -name 'RAW_ADB_CLIENT_V*.md' -o -name 'SCRCPY_125.md' \) | grep -q .; then
  echo 'non-help/version/internal documentation files still present' >&2
  find docs -maxdepth 1 -type f \( -name '*_V[0-9]*.md' -o -name '*V[0-9]*.md' -o -name 'CODE_REVIEW*.md' -o -name 'SOURCE_REVIEW*.md' -o -name 'REGRESSION_TESTS.md' -o -name 'RUNTIME_SIMULATION.md' -o -name 'DOC_HEADERS*.md' -o -name 'RAW_ADB_CLIENT_V*.md' -o -name 'SCRCPY_125.md' \) >&2
  fail=1
fi
for f in docs/ADB_CHEATSHEET.md docs/FRIDA_CHEATSHEET.md docs/NOVNC.md docs/SCRCPY_COMMANDS.md docs/SERVICE.md docs/SPAWN.md docs/CLEAN_WIPE.md docs/WEB_MANAGER.md; do
  [[ -f "$f" ]] || { echo "missing help doc $f" >&2; fail=1; }
done
if grep -q '^# Android Podman Lab Web Manager v[0-9]' README.md; then
  echo 'root README still contains release-history heading' >&2
  fail=1
fi

say 'idempotent install helper present'
grep -q 'record_exists()' androidlab.sh || { echo 'missing record_exists helper' >&2; fail=1; }
grep -q 'skipping default' androidlab.sh || { echo 'install does not skip existing default' >&2; fail=1; }

if [[ "$fail" -ne 0 ]]; then
  echo '[test] FAILED' >&2
  exit 1
fi
echo '[test] OK'
