ARG BASE_IMAGE=localhost/android-emulator-headless:api33-google_apis-x86_64
FROM ${BASE_IMAGE}
RUN apt-get update && apt-get install -y --no-install-recommends \
    xvfb x11vnc fluxbox novnc websockify xterm \
    && rm -rf /var/lib/apt/lists/*
COPY entrypoint-novnc.sh /entrypoint-novnc.sh
RUN chmod +x /entrypoint-novnc.sh
EXPOSE 5554 5555 6080
ENTRYPOINT ["/entrypoint-novnc.sh"]
